apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: niklasheld-niklasheld-poi-map-app-dev
  annotations:
    argocd/app-name: niklasheld-niklasheld-poi-map-app-dev
    backstage.io/kubernetes-id: niklasheld-niklasheld-poi-map-app-dev
    backstage.io/kubernetes-namespace: niklasheld
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=niklasheld-niklasheld-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23Janus2/niklasheld-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/dev-pipelines/ns/niklasheld/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/k8s/ns/niklasheld/deployments/niklasheld-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23blues.6mbu.p1.openshiftapps.com/#https://github.com/Summit23Janus2/niklasheld-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://niklasheld-poi-map-app-niklasheld.apps.summit23blues.6mbu.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/niklasheld"
  system: workshop-system-niklasheld
  consumesApis:
    - gateway-api-niklasheld
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-niklasheld
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/niklasheld"
